name = "driveops-cloud-demo"
main = "worker/src/index.js"
compatibility_date = "2025-08-01"

# Worker serves the frontend in ./public and the API under /api/*
assets = { directory = "./public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "driveops_demo_db"
database_id = "f0da89ef-8609-4db3-afec-5c877752a700"

[[kv_namespaces]]
binding = "KV"
id = "bac3e357d5424f13805b612f5e2a8a4e"

[vars]
APP_NAME = "DriveOps Cloud"
DEMO_MODE = "true"
